// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"go.uber.org/zap"
	"pusher/config"
	"pusher/internal/core/hub"
	"pusher/internal/core/limiter"
	"pusher/internal/core/pool"
	"pusher/internal/infra/rdb"
	"pusher/internal/service/notify"
	"pusher/internal/service/push"
	"pusher/monitor"
	"pusher/transport"
)

// Injectors from wire.go:

// InitApp wire 入口，由 wire 工具自动生成 wire_gen.go。
func InitApp(c *config.Config, logger *zap.Logger) (*App, error) {
	hubHub := hub.NewHub()
	client := rdb.NewClient(c)
	service := notify.NewService(logger)
	bufferPool := provideBufferPool()
	messagePool := pool.NewMessagePool()
	pushService := push.NewService(logger, client, service, bufferPool, messagePool, hubHub)
	monitorMonitor := monitor.NewMonitor(logger, hubHub)
	limiterLimiter := limiter.NewLimiter()
	router := provideRouter(c, logger, hubHub, limiterLimiter, messagePool)
	server := provideHTTPServer(c, router)
	app := &App{
		Logger:    logger,
		Hub:       hubHub,
		PushSvc:   pushService,
		NotifySvc: service,
		Monitor:   monitorMonitor,
		Limiter:   limiterLimiter,
		HTTPSrv:   server,
	}
	return app, nil
}

// wire.go:

// ProviderSet 汇聚所有 wire provider。
var ProviderSet = wire.NewSet(rdb.NewClient, hub.NewHub, limiter.NewLimiter, provideBufferPool, pool.NewMessagePool, notify.NewService, wire.Bind(new(push.Notifier), new(*notify.Service)), push.NewService, monitor.NewMonitor, wire.Bind(new(monitor.Counter), new(*hub.Hub)), provideRouter,

	provideHTTPServer, wire.Struct(new(App), "*"),
)

func provideBufferPool() *pool.BufferPool {
	return pool.NewBufferPool(128)
}

func provideRouter(c *config.Config, logger *zap.Logger, h *hub.Hub, lim *limiter.Limiter, mp *pool.MessagePool) *transport.Router {
	return transport.NewRouter(c.Debug, logger, h, lim, mp)
}

func provideHTTPServer(c *config.Config, router *transport.Router) *Server {
	return NewHTTPServer(c.Addr, router)
}
